"""remove is_ongoing and Product_price_tiers table

Revision ID: d1d74aaab5fb
Revises: 20260810151304
Create Date: 2026-08-11 22:52:54.431887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260811225254'
down_revision: Union[str, Sequence[str], None] = '20260810151304'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_price_tiers_id'), table_name='product_price_tiers')
    op.drop_table('product_price_tiers')
    op.drop_column('products', 'is_ongoing')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_ongoing', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.create_table('product_price_tiers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('min_months', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_months', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price_per_month', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fixed_package_price', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('product_price_tiers_product_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('product_price_tiers_pkey'))
    )
    op.create_index(op.f('ix_product_price_tiers_id'), 'product_price_tiers', ['id'], unique=False)
    # ### end Alembic commands ###
