"""Column min_order_value add to Promotion table

Revision ID: 1790c57eaf7a
Revises: 20260812161953
Create Date: 2026-08-14 09:23:16.577844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260814092316'
down_revision: Union[str, Sequence[str], None] = '20260812161953'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promotions', sa.Column('min_order_value', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('promotions', 'min_order_value')
    # ### end Alembic commands ###
