"""add price column to pets table

Revision ID: 6ca0d2a8fd43
Revises: 20260805102204
Create Date: 2026-08-05 15:57:55.454569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260805155755'
down_revision: Union[str, Sequence[str], None] = '20260805102204'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('price', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pets', 'price')
    # ### end Alembic commands ###
