"""allow to_date to be nullable for ongoing sub, HistoricalData and OnGoingSubscription

Revision ID: 11cb0ef3c7fe
Revises: 20260812112339
Create Date: 2026-08-12 16:19:53.436467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '20260812161953'
down_revision: Union[str, Sequence[str], None] = '20260812112339'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    subscription_type_enum = postgresql.ENUM('HISTORICAL', 'ONGOING', name='subscriptiontypeenum')
    subscription_type_enum.create(op.get_bind())

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_request_items', sa.Column('subscription_type', sa.Enum('HISTORICAL', 'ONGOING', name='subscriptiontypeenum'), nullable=False, server_default='HISTORICAL'))
    op.alter_column('data_request_items', 'to_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data_request_items', 'to_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.drop_column('data_request_items', 'subscription_type')
    # ### end Alembic commands ###
    
    subscription_type_enum = postgresql.ENUM('HISTORICAL', 'ONGOING', name='subscriptiontypeenum')
    subscription_type_enum.drop(op.get_bind())