"""Create product_price_tier table, add columns DataRequestItem and Product tables

Revision ID: 04ac2bc7a7da
Revises: 20260806222656
Create Date: 2026-08-10 13:46:43.279670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260810134643'
down_revision: Union[str, Sequence[str], None] = '20260806222656'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_price_tiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('min_months', sa.Integer(), nullable=False),
    sa.Column('max_months', sa.Integer(), nullable=True),
    sa.Column('price_per_month', sa.Integer(), nullable=False),
    sa.Column('fixed_package_price', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_price_tiers_id'), 'product_price_tiers', ['id'], unique=False)
    op.add_column('data_request_items', sa.Column('calculated_months', sa.Integer(), server_default=sa.text('1'), nullable=False))
    op.add_column('data_request_items', sa.Column('applied_price', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('products', sa.Column('is_ongoing', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'is_ongoing')
    op.drop_column('data_request_items', 'applied_price')
    op.drop_column('data_request_items', 'calculated_months')
    op.drop_index(op.f('ix_product_price_tiers_id'), table_name='product_price_tiers')
    op.drop_table('product_price_tiers')
    # ### end Alembic commands ###
