"""add total_amount to data_requests

Revision ID: 50ef6ab26b18
Revises: 20260810134643
Create Date: 2026-08-10 15:13:04.573161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260810151304'
down_revision: Union[str, Sequence[str], None] = '20260810134643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_requests', sa.Column('total_amount', sa.Integer(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_requests', 'total_amount')
    # ### end Alembic commands ###
