"""add email to users table, add image breed status gender description to pets table

Revision ID: 6cef56cecd03
Revises: 20260804115552
Create Date: 2026-08-05 10:22:04.556968

"""
# 6cef56cecd03
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260805102204'
down_revision: Union[str, Sequence[str], None] = '20260804115552'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('image', sa.String(), nullable=True))
    op.add_column('pets', sa.Column('breed', sa.String(), nullable=True))
    op.add_column('pets', sa.Column('status', sa.String(), nullable=True))
    op.add_column('pets', sa.Column('gender', sa.String(), nullable=True))
    op.add_column('pets', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    op.drop_column('pets', 'description')
    op.drop_column('pets', 'gender')
    op.drop_column('pets', 'status')
    op.drop_column('pets', 'breed')
    op.drop_column('pets', 'image')
    # ### end Alembic commands ###
