"""Add postgresql audit

Revision ID: d45ed9532607
Revises: 20260817151748
Create Date: 2026-08-18 11:20:46.312396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import postgresql_audit 
from postgresql_audit import versioning_manager

# revision identifiers, used by Alembic.
revision: str = '20260818112046'
down_revision: Union[str, Sequence[str], None] = '20260817151748'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('native_transaction_id', postgresql_audit.base.XID8(), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('client_addr', postgresql.INET(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('native_transaction_id', name='transaction_unique_native_tx_id')
    )
    
    op.create_table('activity',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('schema_name', sa.Text(), nullable=True),
    sa.Column('table_name', sa.Text(), nullable=True),
    sa.Column('relid', sa.Integer(), nullable=True),
    sa.Column('issued_at', sa.DateTime(), nullable=True),
    sa.Column('native_transaction_id', postgresql_audit.base.XID8(), nullable=True),
    sa.Column('verb', sa.Text(), nullable=True),
    sa.Column('old_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('changed_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_native_transaction_id'), 'activity', ['native_transaction_id'], unique=False)
    # ### end Alembic commands ###
    # Kích hoạt các hàm Trigger/Function đã được đính kèm vào event của bảng
    conn = op.get_bind()
    activity_table = versioning_manager.activity_cls.__table__
    
    for listener in activity_table.dispatch.after_create:
        listener(activity_table, conn)


def downgrade() -> None:
    """Downgrade schema."""
    # Xóa các function và trigger trước khi xóa bảng (nếu có)
    conn = op.get_bind()
    activity_table = versioning_manager.activity_cls.__table__
    for listener in activity_table.dispatch.before_drop:
        listener(activity_table, conn)
        
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_activity_native_transaction_id'), table_name='activity')
    op.drop_table('activity')
    op.drop_table('transaction')
    # ### end Alembic commands ###