"""Add available dates to Product

Revision ID: c029c158e540
Revises: 20260806124256
Create Date: 2026-08-06 22:26:56.078417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260806222656'
down_revision: Union[str, Sequence[str], None] = '20260806124256'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('available_from', sa.Date(), nullable=True))
    op.add_column('products', sa.Column('available_to', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'available_to')
    op.drop_column('products', 'available_from')
    # ### end Alembic commands ###
